### ISSUE TITLE
`print()` only being overridden in `AppDelegate`

### ISSUE THREAD

**Issue by jonchui** [remirobert/Dotzu#12]
For some reason `print` in other classes than `AppDelegate` is not getting overridden?

**Comment by remirobert** [comment]
Yes that's normal and, because of Swift, you need to import Dotzu on your files to get the print overridden. Sorry for that.

```swift
import Dotzu
```

Maybe the solution would be to add a definition in objective-c file and add to bridging header. So you won't have to import Dotzu each time.
You have a Objective-c pod if you want to try.

**Comment by remirobert** [comment]
Reopen if you still have the issue.

**Comment by liman123** [comment]
Hi, I released [DebugMan](https://github.com/liman123/DebugMan), it is forked from [Dotzu](https://github.com/remirobert/Dotzu).
Welcome to use! 😃 thanks!
@jonchui

**Comment by jonchui** [comment]
I get a 404 when clicking on it?
ᐧ

Jon Chui | YwamKona.org | http://jonchui.com | @jonchui
<http://twitter.com/jonchui>


life verse: Matt 13:44 | our family blog @ vickiandjon.com  | ping me if
you have exciting freelancing projects ;) | 424-241-2484
